use_frameworks!

target 'WLQRCodeScaning_Example' do
  pod 'Masonry'
  pod 'pop'
  pod 'ChameleonFramework'
  pod 'WLQRCodeScaning', :path => '../'

  target 'WLQRCodeScaning_Tests' do
    inherit! :search_paths

    
  end
end
